# Generated by Django 5.0.3 on 2024-04-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCamAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectdetectionevent',
            name='confidence_score_max',
        ),
        migrations.RemoveField(
            model_name='objectdetectionevent',
            name='confidence_score_min',
        ),
    ]
