# Generated by Django 5.0.3 on 2024-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCamAPI', '0002_remove_objectdetectionevent_confidence_score_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdetectionevent',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
